### ISSUE TITLE
[Feature Request] Proxy payload generation at the time of server setup

### ISSUE THREAD

**Issue by r0b1nv4np** [nettitude/PoshC2_Old#13]
When using payloads from a non-domain joined machine, proxy authentication will fail because:

1. Proxy settings are unavailable in IE and registry

1. DefaultNetworkCredentials will not authenticate to the proxy

At the time of server setup, it might be a good idea to ask:

```"Are you using the payload from a non-domain joined machine?" ```
And proceed to obtain the proxy url , port , username and password from the user at the time of setting up the server. 

The current way to navigate this issue is decode the payload and manually add the proxy parameters. The placeholders for proxy parameters already exist in the payload but they cannot be activated until you have an existing active implant. 

Thank you.

**Comment by benpturner** [comment]
Hi,

In the Implant-Handler window, there is pre-implant help which will allow you to do exactly this. You can do the following and it will create you payloads based off the proxy credentials and specified URL. An example is this:

CreateProxyPayload -ProxyURL http://10.0.0.1:8080 -User domain\ben -Pass P@ssw0rd

We could add this to the startup settings, I guess I wanted this to be the default to use the built in settings and have this as an optional. 

Thanks

**Comment by r0b1nv4np** [comment]
Noted ! This is issue can be closed.
